name: Steam Workshop Upload
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to SteamCMD
      
        run: |
          cd steamcmd
          ./steamcmd.sh +login ${{ secrets.STEAM_USER }} ${{ secrets.STEAM_PASSWORD }}

      - name: Upload to Steam Workshop
        run: |
          cd steamcmd
          ./steamcmd.sh +workshop_build_item "../PATH/TO/ITEM" +quit
