name: Steam Workshop Upload
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    environment: e
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to SteamCMD and Update Item
        run: |
          ls /home/ubuntu/actions-runner/_work/AGOTSpanish/AGOTSpanish/
          cd ~/steamcmd
          ./steamcmd.sh +login ${{ secrets.STEAM_USER }} ${{ secrets.STEAM_PASSWORD }}  +workshop_build_item "/home/ubuntu/actions-runner/_work/AGOTSpanish/AGOTSpanish/mod_agotspanish.vdf" +quit
          echo "Item Actualizado"
      - name: Remove Repo Trash
        run: |
          rm -rf /home/ubuntu/actions-runner/_work/AGOTSpanish/AGOTSpanish/
          echo "Repositorio eliminado con exito"
