name: Steam Workshop Upload
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    environment: e
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to SteamCMD and Update Item
        run: |
          cd ~/steamcmd
          ./steamcmd.sh +login ${{ secrets.STEAM_USER }} ${{ secrets.STEAM_PASSWORD }}  +workshop_build_item "../PATH/TO/ITEM" +quit

