name: "Upload to Workshop"

on:
  - push

jobs:
  upload:
  runs-on: self-hosted    
  environment: e
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 1158310
          publishedFileID: 2965385572
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.STEAM_USER }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
