name: "Upload to Workshop"

on:
  - push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 727570
          publishedFileID: 2095592756
        env:
          STEAM_ACCOUNT_NAME: ${{ STEAM_USER }}
          STEAM_PASSWORD: ${{ STEAM_PASSWORD }}
