name: Release Upload
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    environment: e
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Zip code
        run: |
          zip -r /home/ubuntu/actions-runner/_work/AGOTSpanish/AGOTSpanish.zip /home/ubuntu/actions-runner/_work/AGOTSpanish/AGOTSpanish/C/*
          echo "Item Compresed"
      - name: Build and publish release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_RELEASE }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Actualización ${{ env.VERSION }}
          body: |
            ${{ env.VERSION }}
          draft: false
          prerelease: false
          asset_path: /home/ubuntu/actions-runner/_work/AGOTSpanish/AGOTSpanish.zip
          asset_name: AGOTSpanish.zip
          asset_content_type: application/gzip
