name: Release Upload
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    environment: e
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Zip code
        run: |
          zip -r /home/ubuntu/actions-runner/_work/AGOTSpanish/AGOTSpanish.zip /home/ubuntu/actions-runner/_work/AGOTSpanish/AGOTSpanish/C/*
          echo "Item Compresed"
      - name: Get latest release version
        id: get_latest_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.TOKEN_RELEASE }}
          tag_name: latest
          prerelease: false
      - name: Update version in code
        run: |
          sed -i "s/VERSION = .*/VERSION = '${{ steps.get_latest_release.outputs.tag_name }}'/g" mycode.py
      - name: Build and publish release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_RELEASE }}
        with:
          tag_name: ${{ steps.get_latest_release.outputs.tag_name }}
          release_name: Actualización ${{ steps.get_latest_release.outputs.tag_name }}
          body: |
            ${{ steps.get_latest_release.outputs.tag_name }}
          draft: false
          prerelease: false
          asset_path: /home/ubuntu/actions-runner/_work/AGOTSpanish/AGOTSpanish.zip
          asset_name: AGOTSpanish.zip
           asset_content_type: application/gzip
