name: Verificar archivos de idioma

on:
  push:
    branches:
      - main
      - prod
    paths:
      - '**.yml'
  pull_request:
    branches:
      - main
      - prod
    paths:
      - '**.yml'
jobs:
  verificacion:
    runs-on: self-hosted
    environment: Tests
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2
      - name: Verificar archivos de idioma
        run: |
          for archivo in $(git diff --name-only HEAD^..HEAD | grep '\.yml$'); do
              python ~/procesar_archivo.py ~/actions-runner/_work/AGOTSpanish/AGOTSpanish/ || exit 1
          done
      - name: Finalizar verificación
        run: echo "Verificación de archivos de idioma completada satisfactoriamente."
